[ci] Disable unittest job due to libtorch execstack issue.
ImportError: libtorch_cpu.so: cannot enable executable stack as shared object requires: Invalid argument