[ci] Remove execstack flag from libtorch binaries.
ImportError: libtorch_cpu.so: cannot enable executable stack as shared object requires: Invalid argument